language: node_js

node_js:
  - node

deploy:
  provider: npm
  email: dr.evil@krtn.eu
  api_key:
    secure: ccmnQ289NQcDDincQH1hxppCSXT421pCrwcif+ue31uWa2b6C/dQGCjJQ9gUjWOg4rILbU3SBopS8Qdv6N3DwJDrAAGUpLXFsrxbB4taT1Aeg6+UrBShYpbgdR7sCiw6k2WYcYqpphCLUutX+Zl9ob9g1rNmyNbe2zBKqnog163OBXrZC3VeFuQ5EozET/8bESNLje2PpT9uF8MWt64uZDslZpnIXgMfpB4f0840DmGm9roFpubEMEAOdYkYp2AxVX6baf8W6PAWWjjByhV81nUyjrWsbxOsFwYzvxLYjEFWmxdb4Xw5zq83SAl60jsZq9jgRMHsuUOpwEHg0cMfeEhHnj2nEog3Fdcqj/YdUoHfwkjE/EmYUQsdxWFK3mqEpS9UUDW/CU8yC4el2b7Mub0ny3e/1uyjH9zdUtktrJV666vh3QuVuZitgPokHLx931zjUxNdbhqpVf3t4TeuXbJ/jpEVsrY0/W7Gf56Xdudm7yiy7NmF4U6aCvNl05rzP4zzNtddT3y00qv/TgVcgWOwtFnsmvhQ3AdEgFzDqEnDx8Ow+1NyCWuEmA3KBoPRaMVwUfqnCHwflOolaR9rDlZsJEfZGoE3BCppLHtZOQuDjp8BFWICl0Wm08pww2WCkLgNMk88duKzubNPbXknrJA6mhLFjTsoZJZFE9MW7DY=
  on:
    tags: true
    repo: v12/fast-crc32
